[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia_eth="",arb_sepolia=""}
remapping = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
